# volumes:
#   hsr-data:
#     external: true
services:
  # postgres:
  #   image: postgres:14.5-bullseye
  #   volumes:
  #     - hsr-data:/var/lib/postgresql/data
  #   environment:
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_USER: user
  #     POSTGRES_DB: hsr_db
  #   ports:
  #     - 15432:5432
  # fastapi:
  #   environment:
  #     CORS_HOST: http://localhost:3000
  #     DATABASE_URL: postgresql://user:password@postgres/hsr_db
  #   build:
  #     context: api
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 8000:8000
  #   volumes:
  #     - ./api:/app

  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app
    volumes:
      - ./ghi:/app
    ports:
      - "3000:3000"
    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: http://localhost:3000
      # REACT_APP_API_HOST: ${REACT_APP_API_HOST}
